<html>
<head></head>
<style type="text/css">
body
{
background-color:#D6D6CD;
}

table.board
{
border-style:solid;
border-width:2px;
border-right-width:0px;
}

.center
{
position:absolute;
top:145px;
right:470px;
width:40%;
}

.pic
{
position:absolute;
top:115px;
right:630px;
width:40%;

}

.banner
{
position:absolute;
top:50px;
right:470px;
width:40%;

}

</style>

<div class="banner">
	<img src="/resource/Rackspace_banner" align="left"/>
</div>

<div class="pic">
	<img src="/resource/ppbg" align="left"/>
</div>

<div class="center">
	<table class="board" width="350" height="270" align="left" bgcolor="#F8F8FF">
		<td>
		<font color="#858580"><b>Welcome to the Rackspace Partner Program.</b>Our channel program is designed to assist you in profiting from the technological shift from traditional on-premise server management to cloud-hosted services. Whether you are looking to own the customer relationship or refer business opportunities directly, our program is flexible to make you successful. Please enter your log-in information to enter the portal. </font>
		</td>
	</table>
</div>
</html>